# Generated by Django 5.0.4 on 2024-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
